/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Certification {
  'id' : bigint,
  'url' : string,
  'date' : string,
  'name' : string,
  'issuer' : string,
}
export interface Education {
  'id' : bigint,
  'gpa' : string,
  'field' : string,
  'endDate' : string,
  'institution' : string,
  'degree' : string,
  'startDate' : string,
}
export interface Language {
  'id' : bigint,
  'language' : string,
  'proficiency' : string,
}
export interface PersonalInfo {
  'linkedin' : string,
  'name' : string,
  'email' : string,
  'website' : string,
  'jobTitle' : string,
  'phone' : string,
  'location' : string,
}
export interface Project {
  'id' : bigint,
  'url' : string,
  'bullets' : Array<string>,
  'name' : string,
  'description' : string,
}
export interface ResumeData {
  'projects' : Array<Project>,
  'targetJobDescription' : string,
  'education' : Array<Education>,
  'workExperience' : Array<WorkExperience>,
  'languages' : Array<Language>,
  'summary' : string,
  'certifications' : Array<Certification>,
  'personalInfo' : PersonalInfo,
  'skills' : Array<SkillCategory>,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SkillCategory {
  'id' : bigint,
  'category' : string,
  'skills' : Array<string>,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkExperience {
  'id' : bigint,
  'title' : string,
  'endDate' : [] | [string],
  'bullets' : Array<string>,
  'company' : string,
  'isCurrent' : boolean,
  'location' : string,
  'startDate' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteResume' : ActorMethod<[], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getResume' : ActorMethod<[], [] | [ResumeData]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPaid' : ActorMethod<[Principal], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveResume' : ActorMethod<[ResumeData], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];