/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'bullets' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Education = IDL.Record({
  'id' : IDL.Nat,
  'gpa' : IDL.Text,
  'field' : IDL.Text,
  'endDate' : IDL.Text,
  'institution' : IDL.Text,
  'degree' : IDL.Text,
  'startDate' : IDL.Text,
});
export const WorkExperience = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'endDate' : IDL.Opt(IDL.Text),
  'bullets' : IDL.Vec(IDL.Text),
  'company' : IDL.Text,
  'isCurrent' : IDL.Bool,
  'location' : IDL.Text,
  'startDate' : IDL.Text,
});
export const Language = IDL.Record({
  'id' : IDL.Nat,
  'language' : IDL.Text,
  'proficiency' : IDL.Text,
});
export const Certification = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'issuer' : IDL.Text,
});
export const PersonalInfo = IDL.Record({
  'linkedin' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'jobTitle' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const SkillCategory = IDL.Record({
  'id' : IDL.Nat,
  'category' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
});
export const ResumeData = IDL.Record({
  'projects' : IDL.Vec(Project),
  'targetJobDescription' : IDL.Text,
  'education' : IDL.Vec(Education),
  'workExperience' : IDL.Vec(WorkExperience),
  'languages' : IDL.Vec(Language),
  'summary' : IDL.Text,
  'certifications' : IDL.Vec(Certification),
  'personalInfo' : PersonalInfo,
  'skills' : IDL.Vec(SkillCategory),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteResume' : IDL.Func([], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getResume' : IDL.Func([], [IDL.Opt(ResumeData)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isPaid' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveResume' : IDL.Func([ResumeData], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'bullets' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Education = IDL.Record({
    'id' : IDL.Nat,
    'gpa' : IDL.Text,
    'field' : IDL.Text,
    'endDate' : IDL.Text,
    'institution' : IDL.Text,
    'degree' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const WorkExperience = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'endDate' : IDL.Opt(IDL.Text),
    'bullets' : IDL.Vec(IDL.Text),
    'company' : IDL.Text,
    'isCurrent' : IDL.Bool,
    'location' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const Language = IDL.Record({
    'id' : IDL.Nat,
    'language' : IDL.Text,
    'proficiency' : IDL.Text,
  });
  const Certification = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'issuer' : IDL.Text,
  });
  const PersonalInfo = IDL.Record({
    'linkedin' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'jobTitle' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const SkillCategory = IDL.Record({
    'id' : IDL.Nat,
    'category' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
  });
  const ResumeData = IDL.Record({
    'projects' : IDL.Vec(Project),
    'targetJobDescription' : IDL.Text,
    'education' : IDL.Vec(Education),
    'workExperience' : IDL.Vec(WorkExperience),
    'languages' : IDL.Vec(Language),
    'summary' : IDL.Text,
    'certifications' : IDL.Vec(Certification),
    'personalInfo' : PersonalInfo,
    'skills' : IDL.Vec(SkillCategory),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteResume' : IDL.Func([], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getResume' : IDL.Func([], [IDL.Opt(ResumeData)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isPaid' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveResume' : IDL.Func([ResumeData], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };